select * from customer limit 10;

-- q1) What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- q2) which customer used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- q3) which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as average_review_rating 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- q4) Compare the average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2) as average_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- q5) Do subscribed customers spend more? compare average spend and total revenue between subscriber and non-subscriber?
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend desc;

-- q6) which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as percentage_of_purchases
from customer
group by item_purchased
order by percentage_of_purchases desc
limit 5;

-- q7) segment customers into new, returning and loyal based on their total number of previous purchase, 
--and show the count of each segment?
with customer_type as(
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'NEW'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer	
)
select customer_segment, count(customer_id) as number_of_customers
from customer_type
group by customer_segment;

-- q8) what are the top 3 most purchased products within each category?
with purchased_products as(
select category, item_purchased, count(customer_id) as total_orders, row_number() over(partition by category 
order by count(customer_id) desc) as rankings
from customer
group by category, item_purchased
)
select category, item_purchased, total_orders, rankings
from purchased_products
where rankings <=3;

-- q9) Are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

-- q10) What is the revenue contribution for each age group?
select age_group, sum(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc;



